force-app/main/default/objects/Consultant__c.object
<CustomObject>
    <label>Consultant</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Consultant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Too Less</fullName>
                </value>
                <value>
                    <fullName>Minimum</fullName>
                </value>
                <value>
                    <fullName>Intermediate</fullName>
                </value>
                <value>
                    <fullName>Maximum</fullName>
                </value>
                <value>
                    <fullName>Too High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c.object
<CustomObject>
    <fields>
        <fullName>Consultant__c</fullName>
        <label>Consultant</label>
        <referenceTo>Consultant__c</referenceTo>
        <relationshipLabel>Project Teams</relationshipLabel>
        <relationshipName>Project_Teams</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Teams</relationshipLabel>
        <relationshipName>Project_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Team</label>
    <nameField>
        <label>Project Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/helperProject.cls
public class helperProject {
    public static void method1(List<Project__c> newLst)
    {
        for(Project__c pro: newLst){
            pro.name+= +' '+pro.category__c;
        }
    }
    
    public static void method2(List<Project__c> newLst,Map<id,Project__c> oldMap)
    {
       List<Project_team__c> lstuser=new List<Project_team__c>();
        List<Project__c> lstpro=new List<Project__c>();
        for(Project__c pro:newLst){
            if(oldMap.get(pro.id).Project_manager__c!=pro.Project_manager__c)
            {
                lstpro.add(pro);
            }
        }
        List<Task> ta =new List<Task>();
        for(Project_Team__c pteam: [select project__c,Consultant__c 
                                    from Project_Team__c 
                                    where project__c in:lstpro])
        {
            Task t = new Task();
            t.description = 'Notification';
            t.Subject='Project manager is changed';
            t.WhatId = pteam.Consultant__c;
            ta.add(t);
                   }
        insert ta;
        }
}