force-app/main/default/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MyRelatedTransactions.cls
public class MyRelatedTransactions {
    public Contact con;
    public List<Transaction__c> trans;
    public MyRelatedTransactions(){
        ID id1=ApexPages.currentPage().getParameters().get('id');
        if(id1!=null)
        {
            trans=[select contact__r.name from transaction__c where id=:id1];
            
        }
        else
        {
          trans=[select account__r.name from transaction__c] ;  
        }
    }
    public Contact getContact(){
        return con;
    }

}